# Generated by Django 4.0.3 on 2022-05-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='store',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
