# Generated by Django 4.0.3 on 2022-05-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_profile_dob_profile_location_profile_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
