# Generated by Django 4.0.3 on 2022-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requested_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_user', models.CharField(max_length=50)),
                ('requested_item', models.CharField(max_length=50)),
                ('requester_phone', models.IntegerField()),
                ('requester_budget', models.IntegerField()),
                ('requester_messsage', models.CharField(max_length=200)),
                ('request_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
